### ISSUE TITLE
No module empyricalRMT found

### ISSUE THREAD

**Issue by jalfonsi** [stfxecutables/empyricalRMT#1]
After successfull installation with pip, when I import modules as in the tutorial in "Basic Usage" in Jupyter notebook it gives ModuleNotFound Error. So it's pretty impossible to go further.

**Comment by DM-Berger** [comment]
Hi Jessica

Firstly, thanks for your interest in the library, and finding this issue!

Right now, this library is currently undergoing a massive rewrite (especially as regards the output and automation of the various unfolding procedures) and is still in very early development. It really should still be considered pre-alpha, since it also hasn't received any kind of real public release. So for now, I'm going to close this issue, and I've updated the README to reflect the development state.

There should actually be a new, properly-functional major release out soon (2-3 weeks), now that I have some time to focus on this for a bit. If you're still interested then, and find an issue (or still have this same issue) let me know.

**Comment by jalfonsi** [comment]
Thanks for answering! I'll be happy to try it again in the few next weeks if something new is out!
